// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxndfqlmzyjewoflknzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4bmRmcWxtenlqZXdvZmxrbnpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDgxNDksImV4cCI6MjA2OTcyNDE0OX0.6Pu-VlOxer32Wty2SOZfDMWHRuewtv8ITXmJ1cBY08w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});